# This is a basic workflow to help you get started with Actions

name: Latest Testing

# Controls when the action will run.
on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          environment: testing

      - name: Get latest deployment
        id: get_last_deployment
        uses: ./
        with:
          environment: testing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update deployment status db (success)
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          deployment-id: ${{steps.get_last_deployment.outputs.deployment_id}}
          state: "success"
